FROM python:3.12-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ default-libmysqlclient-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src/

# Run Kafka Producer in live schedule mode
CMD ["python", "-u", "src/pipeline/kafka_producer.py", "--mode", "live"]
