services:
  zookeeper:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  redis:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    image: redis:7.2-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  api:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    build:
      context: .
      dockerfile: Dockerfile.api
    #image: 'ptn_anomaly_detection-api:latest'
    container_name: ptn_anomaly_detection-api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=cowptn
      - KAFKA_BROKERS=kafka:29092
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - redis

  ui:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    build:
      context: .
      dockerfile: Dockerfile.ui
    #image: 'ptn_anomaly_detection-ui:latest'
    container_name: ptn_anomaly_detection-ui
    ports:
      - "80:80"
    depends_on:
      - api

  consumer:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    build:
      context: .
      dockerfile: Dockerfile.consumer
    #image: 'ptn_anomaly_detection-consumer:latest'
    container_name: ptn_anomaly_detection-consumer
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=cowptn
      - KAFKA_BROKERS=kafka:29092
      - REDIS_HOST=redis
      - API_URL=http://api:8000
    depends_on:
      - kafka
      - redis
      - api

  producer:
    platform: linux/arm64 # linux/amd64, windows/amd64, ...
    build:
      context: .
      dockerfile: Dockerfile.producer
    #image: 'ptn_anomaly_detection-producer:latest'
    container_name: ptn_anomaly_detection-producer
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=cowptn
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
